{% set name = "databind.json" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/databind.json-{{ version }}.tar.gz
  sha256: b53b51cecb59d8b2f6eaafdc1f39e1ab887f6c4d99bcd6ca09e42f7df6175641

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - databind.core >=1.2.2,<2.0.0
    - nr.optional >=0.1.1,<1.0.0
    - nr.parsing.date >=1.0.1,<2.0.0
    - nr.preconditions >=0.0.4,<1.0.0
    - python >={{ python_min }},<4.0
    - typing-extensions <4.0.0,>=3.10.0

test:
  imports:
    - databind
    - databind.json
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NiklasRosenstein/python-databind
  summary: De-/serialize Python dataclasses to or from JSON payloads. Compatible with Python 3.7 and newer.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
